import { defineConfig } from "eslint/config"
import js from "@eslint/js"

/*
  ESLint
  Documentation: https://eslint.org/docs/latest/rules/
*/
export default defineConfig({
  extends: [js.configs.recommended],
  name: "vauldex-eslint-configs/eslint",
  rules: {
    "accessor-pairs": "warn",
    "array-callback-return": "error",
    "camelcase": ["error", { properties: "always" }],
    "complexity": ["error", 10],
    "curly": "error",
    "default-case-last": "error",
    "dot-notation": "error",
    "eqeqeq": ["error", "always", { null: "ignore" }],
    "guard-for-in": "error",
    "id-length": ["error", { min: 2 }],
    "max-depth": ["error", { max: 3 }],
    "max-nested-callbacks": ["error", { max: 3 }],
    "new-cap": "error",
    "no-alert": "error",
    "no-await-in-loop": "error",
    "no-bitwise": "error",
    "no-caller": "error",
    "no-console": "error",
    "no-constructor-return": "error",
    "no-continue": "error",
    "no-div-regex": "error",
    "no-duplicate-imports": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-implicit-coercion": "error",
    "no-implied-eval": "error",
    "no-inner-declarations": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-multi-assign": "error",
    "no-multi-str": "error",
    "no-nested-ternary": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-object-constructor": "error",
    "no-octal-escape": "error",
    "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
    "no-promise-executor-return": "error",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-undef-init": "off",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": "error",
    "no-unreachable-loop": "error",
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-void": ["error", { allowAsStatement: true }],
    "operator-assignment": ["error", "always"],
    "prefer-arrow-callback": "error",
    "prefer-destructuring": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "require-atomic-updates": "error",
    "func-style": ["error", "expression"],
    "yoda": "error",
  },
})
